# Stage 1 - Build
FROM eclipse-temurin:17-jdk AS builder

WORKDIR /app

COPY src/Main.java .
RUN javac Main.java

# Stage 2 - Runtime
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/Main.class .
COPY quotes.txt .

EXPOSE 8000

CMD ["java", "Main"]
